syntax on
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set hlsearch
set incsearch
set ignorecase
set smartcase
set cursorline
set wildmenu
set showmatch
set encoding=utf-8
set fileencoding=utf-8
set clipboard=unnamedplus
set mouse=a
set scrolloff=8
set signcolumn=yes
set updatetime=300
set background=dark
